Repository profunktor/redis4cats, pull requests merged in 2020-12, with the labels that each got.

#433 Fix pipelining test + add caveats documentation
  modules/tests/src/test/scala/dev/profunktor/redis4cats/RedisSpec.scala
  modules/tests/src/test/scala/dev/profunktor/redis4cats/TestScenarios.scala
  site/docs/pipelining.md
Labels: documentation

#436 Update sbt script version
  .github/workflows/ci.yml
  .github/workflows/publish-site.yml
  .github/workflows/release.yml
  shell.nix
Labels: internal

#439 Update mdoc, sbt-mdoc to 2.2.14
  project/plugins.sbt
Labels: dependency-update

#440 Update cats-core, cats-effect, cats-testkit to 2.3.1
  project/Dependencies.scala
Labels: dependency-update

#438 Update munit, munit-scalacheck to 0.7.20
  project/Dependencies.scala
Labels: dependency-update

#437 Update sbt to 1.4.5
  project/build.properties
Labels: dependency-update

#441 Update fs2-core to 2.5.0
  project/Dependencies.scala
Labels: dependency-update

#442 Update sbt-microsites to 1.3.0
  project/plugins.sbt
Labels: dependency-update

#443 Update sbt to 1.4.6
  project/build.properties
Labels: dependency-update
